# Generated by Django 4.2.4 on 2023-08-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=4)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('has_entered_invite_code', models.BooleanField(default=False)),
                ('used_invite_codes', models.ManyToManyField(blank=True, related_name='used_by', to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_phone', models.CharField(max_length=11)),
                ('inviter_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_phone', to='main.userprofile')),
                ('used_invite_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_invite_code', to='main.userprofile')),
            ],
        ),
    ]
